server:
  port: 8081


spring:
  application:
    name: association
  datasource:
    url: jdbc:mysql://106.14.170.74:3306/association?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1hblsqt!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
logging:
  level:
    com:
      inyta:
        assciation:
          mapper: debug

association:
  file:
    upload:
      path: /home/static/res/association
    read:
      path: /res/association
  application:
    host: http://106.14.170.74
